"""Download all Kaggle simulation logs for one submission.

This script:

1. Lists every Episode associated with a Kaggle submission ID.
2. Downloads the replay JSON for each Episode.
3. Downloads logs for agent indexes 0 and 1.
4. Writes a manifest.csv summarizing successes and failures.
5. Can be rerun safely; already-downloaded files are skipped by default.
6. Optionally creates a ZIP archive for sharing.

The official Kaggle CLI commands used are:

    kaggle competitions episodes <submission_id> -v
    kaggle competitions replay <episode_id> -p <directory>
    kaggle competitions logs <episode_id> <agent_index> -p <directory>

Authentication is required for Episode discovery and log download.
Do not commit kaggle.json or API tokens to Git.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import shutil
import subprocess
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable, Sequence


@dataclass
class EpisodeRecord:
    episode_id: int
    create_time: str = ""
    end_time: str = ""
    state: str = ""
    episode_type: str = ""


@dataclass
class DownloadRecord:
    submission_id: int
    episode_id: int
    episode_state: str
    detected_submission_agent_index: str
    replay_status: str
    agent_0_log_status: str
    agent_1_log_status: str
    error: str


def run_kaggle(
    args: Sequence[str],
    *,
    attempts: int = 3,
    retry_wait: float = 2.0,
) -> subprocess.CompletedProcess[str]:
    """Run the Kaggle CLI with retries and return its completed process."""
    command = [sys.executable, "-m", "kaggle", *args]
    last_result: subprocess.CompletedProcess[str] | None = None

    for attempt in range(1, attempts + 1):
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        last_result = result

        if result.returncode == 0:
            return result

        if attempt < attempts:
            wait = retry_wait * attempt
            print(
                f"Command failed; retrying in {wait:.1f}s "
                f"({attempt}/{attempts}): {' '.join(command)}"
            )
            time.sleep(wait)

    assert last_result is not None
    message = (last_result.stderr or last_result.stdout).strip()
    raise RuntimeError(
        f"Kaggle CLI failed with exit code {last_result.returncode}:\n"
        f"{' '.join(command)}\n{message}"
    )


def clean_cli_lines(text: str) -> list[str]:
    """Remove blank and warning lines before CSV parsing."""
    return [
        line
        for line in text.splitlines()
        if line.strip() and not line.lstrip().startswith("Warning:")
    ]


def find_csv_header(lines: Sequence[str], expected_first_column: str) -> int:
    """Find the CSV header line generated by Kaggle's verbose output."""
    target = expected_first_column.lower()

    for index, line in enumerate(lines):
        first = line.split(",", 1)[0].strip().strip('"').lower()
        if first == target:
            return index

    raise ValueError(
        f"Could not find CSV header whose first column is "
        f"{expected_first_column!r}.\n"
        f"CLI output:\n" + "\n".join(lines[:30])
    )


def list_submission_episodes(submission_id: int) -> list[EpisodeRecord]:
    """Return all Episodes currently associated with a submission."""
    result = run_kaggle(
        [
            "competitions",
            "episodes",
            str(submission_id),
            "-v",
        ]
    )

    lines = clean_cli_lines(result.stdout)
    header_index = find_csv_header(lines, "id")
    reader = csv.DictReader(lines[header_index:])

    records: list[EpisodeRecord] = []
    for row in reader:
        raw_id = str(row.get("id", "")).strip()
        if not raw_id.isdigit():
            continue

        records.append(
            EpisodeRecord(
                episode_id=int(raw_id),
                create_time=str(
                    row.get("createTime")
                    or row.get("create_time")
                    or ""
                ),
                end_time=str(
                    row.get("endTime")
                    or row.get("end_time")
                    or ""
                ),
                state=str(row.get("state") or ""),
                episode_type=str(
                    row.get("type")
                    or row.get("episodeType")
                    or ""
                ),
            )
        )

    # Preserve the CLI ordering while removing accidental duplicates.
    unique: dict[int, EpisodeRecord] = {}
    for record in records:
        unique.setdefault(record.episode_id, record)

    return list(unique.values())


def directory_has_json(path: Path) -> bool:
    return path.is_dir() and any(path.glob("*.json"))


def download_replay(
    episode_id: int,
    output_dir: Path,
    *,
    overwrite: bool,
) -> tuple[str, Path | None]:
    """Download one Episode replay using the official Kaggle CLI."""
    output_dir.mkdir(parents=True, exist_ok=True)

    existing = sorted(output_dir.glob("*.json"))
    if existing and not overwrite:
        return "skipped_existing", existing[0]

    if overwrite:
        for path in existing:
            path.unlink()

    run_kaggle(
        [
            "competitions",
            "replay",
            str(episode_id),
            "-p",
            str(output_dir),
        ]
    )

    downloaded = sorted(output_dir.glob("*.json"))
    if not downloaded:
        raise FileNotFoundError(
            f"Kaggle CLI reported success but no replay JSON appeared in "
            f"{output_dir}"
        )

    return "downloaded", downloaded[0]


def download_agent_log(
    episode_id: int,
    agent_index: int,
    output_dir: Path,
    *,
    overwrite: bool,
) -> str:
    """Download one agent's log JSON using the official Kaggle CLI."""
    output_dir.mkdir(parents=True, exist_ok=True)

    existing = sorted(output_dir.glob("*.json"))
    if existing and not overwrite:
        return "skipped_existing"

    if overwrite:
        for path in existing:
            path.unlink()

    run_kaggle(
        [
            "competitions",
            "logs",
            str(episode_id),
            str(agent_index),
            "-p",
            str(output_dir),
        ]
    )

    downloaded = sorted(output_dir.glob("*.json"))
    if not downloaded:
        raise FileNotFoundError(
            f"Kaggle CLI reported success but no agent log JSON appeared in "
            f"{output_dir}"
        )

    return "downloaded"


def scalar_matches_submission(value: object, submission_id: int) -> bool:
    if isinstance(value, bool) or value is None:
        return False
    return str(value).strip() == str(submission_id)


def object_contains_submission_id(
    value: object,
    submission_id: int,
    *,
    parent_key: str = "",
) -> bool:
    """Recursively find a submission ID only under submission-like keys."""
    if isinstance(value, dict):
        for key, child in value.items():
            key_text = str(key).lower()
            if "submission" in key_text:
                if scalar_matches_submission(child, submission_id):
                    return True
                if isinstance(child, (dict, list)) and object_contains_submission_id(
                    child,
                    submission_id,
                    parent_key=key_text,
                ):
                    return True
            elif isinstance(child, (dict, list)):
                if object_contains_submission_id(
                    child,
                    submission_id,
                    parent_key=key_text,
                ):
                    return True
        return False

    if isinstance(value, list):
        return any(
            object_contains_submission_id(
                child,
                submission_id,
                parent_key=parent_key,
            )
            for child in value
        )

    return (
        "submission" in parent_key
        and scalar_matches_submission(value, submission_id)
    )


def detect_submission_agent_index(
    replay_path: Path | None,
    submission_id: int,
) -> int | None:
    """Best-effort detection of whether the submission was agent 0 or 1.

    Kaggle replay schemas can evolve. This intentionally checks several
    common top-level containers and then falls back to a bounded recursive
    search. Failure is harmless because both agent logs are downloaded.
    """
    if replay_path is None or not replay_path.exists():
        return None

    try:
        data = json.loads(replay_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        return None

    candidate_lists: list[list[object]] = []

    if isinstance(data, dict):
        for key in ("agents", "participants", "players"):
            value = data.get(key)
            if isinstance(value, list):
                candidate_lists.append(value)

        info = data.get("info")
        if isinstance(info, dict):
            for key in ("agents", "participants", "players"):
                value = info.get(key)
                if isinstance(value, list):
                    candidate_lists.append(value)

        configuration = data.get("configuration")
        if isinstance(configuration, dict):
            for key in ("agents", "participants", "players"):
                value = configuration.get(key)
                if isinstance(value, list):
                    candidate_lists.append(value)

    for items in candidate_lists:
        for index, item in enumerate(items[:2]):
            if object_contains_submission_id(item, submission_id):
                return index

    return None


def write_episode_list(
    path: Path,
    episodes: Iterable[EpisodeRecord],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "episode_id",
        "create_time",
        "end_time",
        "state",
        "episode_type",
    ]
    with path.open("w", newline="", encoding="utf-8-sig") as file:
        writer = csv.DictWriter(file, fieldnames=fields)
        writer.writeheader()
        for episode in episodes:
            writer.writerow(asdict(episode))


def write_manifest(path: Path, records: Iterable[DownloadRecord]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "submission_id",
        "episode_id",
        "episode_state",
        "detected_submission_agent_index",
        "replay_status",
        "agent_0_log_status",
        "agent_1_log_status",
        "error",
    ]
    with path.open("w", newline="", encoding="utf-8-sig") as file:
        writer = csv.DictWriter(file, fieldnames=fields)
        writer.writeheader()
        for record in records:
            writer.writerow(asdict(record))


def create_zip(source_dir: Path, zip_path: Path) -> Path:
    zip_path.parent.mkdir(parents=True, exist_ok=True)
    if zip_path.suffix.lower() == ".zip":
        base_name = zip_path.with_suffix("")
    else:
        base_name = zip_path

    produced = Path(
        shutil.make_archive(
            str(base_name),
            "zip",
            root_dir=source_dir.parent,
            base_dir=source_dir.name,
        )
    )
    return produced


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Download every Episode replay and both agents' logs for a "
            "Kaggle simulation submission."
        )
    )
    parser.add_argument(
        "--submission",
        type=int,
        required=True,
        help="Kaggle submission ID.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help=(
            "Output directory. Default: "
            "data/submissions/submission_<ID>"
        ),
    )
    parser.add_argument(
        "--sleep",
        type=float,
        default=1.0,
        help="Seconds to wait between Episodes. Default: 1.0",
    )
    parser.add_argument(
        "--max-episodes",
        type=int,
        default=0,
        help="Process only the first N Episodes; 0 means all.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Redownload files that already exist.",
    )
    parser.add_argument(
        "--zip",
        action="store_true",
        help="Create a ZIP archive after downloading.",
    )
    parser.add_argument(
        "--zip-path",
        type=Path,
        help="Optional path for the ZIP archive.",
    )
    args = parser.parse_args()

    output_root = (
        args.output
        if args.output is not None
        else Path("data")
        / "submissions"
        / f"submission_{args.submission}"
    )
    output_root = output_root.resolve()
    output_root.mkdir(parents=True, exist_ok=True)

    print(f"Submission ID: {args.submission}")
    print(f"Output directory: {output_root}")
    print("Discovering Episodes...")

    episodes = list_submission_episodes(args.submission)
    if args.max_episodes > 0:
        episodes = episodes[: args.max_episodes]

    if not episodes:
        print(
            "No Episodes were returned. The submission may not have played "
            "yet, or the Kaggle credentials may not have access."
        )
        return

    print(f"Episodes found: {len(episodes)}")
    write_episode_list(output_root / "episodes.csv", episodes)

    manifest: list[DownloadRecord] = []

    for number, episode in enumerate(episodes, start=1):
        episode_dir = output_root / "episodes" / str(episode.episode_id)
        replay_dir = episode_dir / "replay"
        log_0_dir = episode_dir / "agent_0"
        log_1_dir = episode_dir / "agent_1"

        print(
            f"\n[{number}/{len(episodes)}] "
            f"Episode {episode.episode_id} "
            f"(state={episode.state or 'unknown'})"
        )

        replay_status = "not_attempted"
        log_0_status = "not_attempted"
        log_1_status = "not_attempted"
        errors: list[str] = []
        replay_path: Path | None = None

        try:
            replay_status, replay_path = download_replay(
                episode.episode_id,
                replay_dir,
                overwrite=args.overwrite,
            )
            print(f"  Replay: {replay_status}")
        except Exception as exc:
            replay_status = "failed"
            errors.append(
                f"replay: {type(exc).__name__}: {exc}"
            )
            print(f"  Replay: FAILED: {exc}")

        detected_index = detect_submission_agent_index(
            replay_path,
            args.submission,
        )
        detected_text = (
            str(detected_index)
            if detected_index is not None
            else ""
        )
        if detected_index is not None:
            print(f"  Submitted agent appears to be agent {detected_index}")
        else:
            print(
                "  Submitted agent index could not be detected; "
                "both logs will still be saved."
            )

        for agent_index, target_dir in (
            (0, log_0_dir),
            (1, log_1_dir),
        ):
            try:
                status = download_agent_log(
                    episode.episode_id,
                    agent_index,
                    target_dir,
                    overwrite=args.overwrite,
                )
                print(f"  Agent {agent_index} log: {status}")
                if agent_index == 0:
                    log_0_status = status
                else:
                    log_1_status = status
            except Exception as exc:
                status = "failed"
                errors.append(
                    f"agent_{agent_index}: "
                    f"{type(exc).__name__}: {exc}"
                )
                print(f"  Agent {agent_index} log: FAILED: {exc}")
                if agent_index == 0:
                    log_0_status = status
                else:
                    log_1_status = status

        manifest.append(
            DownloadRecord(
                submission_id=args.submission,
                episode_id=episode.episode_id,
                episode_state=episode.state,
                detected_submission_agent_index=detected_text,
                replay_status=replay_status,
                agent_0_log_status=log_0_status,
                agent_1_log_status=log_1_status,
                error=" | ".join(errors),
            )
        )
        write_manifest(output_root / "manifest.csv", manifest)

        if number < len(episodes) and args.sleep > 0:
            time.sleep(args.sleep)

    success_replays = sum(
        record.replay_status in {"downloaded", "skipped_existing"}
        for record in manifest
    )
    success_logs = sum(
        status in {"downloaded", "skipped_existing"}
        for record in manifest
        for status in (
            record.agent_0_log_status,
            record.agent_1_log_status,
        )
    )
    failures = sum(bool(record.error) for record in manifest)

    print("\n=== Summary ===")
    print(f"Episodes processed: {len(manifest)}")
    print(f"Replays available: {success_replays}/{len(manifest)}")
    print(f"Agent logs available: {success_logs}/{len(manifest) * 2}")
    print(f"Episodes with at least one failure: {failures}")
    print(f"Manifest: {output_root / 'manifest.csv'}")

    if args.zip or args.zip_path:
        zip_path = (
            args.zip_path
            if args.zip_path is not None
            else output_root.parent / f"{output_root.name}.zip"
        )
        produced = create_zip(output_root, zip_path.resolve())
        print(f"ZIP: {produced}")


if __name__ == "__main__":
    main()
